/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package despacho.Vista;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author gerar
 */
public class ProcedimientoSwing extends javax.swing.JPanel {

    /**
     * Creates new form ProcedimientoSwing
     */
    public ProcedimientoSwing() {
        initComponents();
        //Creamos el conjunto de pestañas
        JTabbedPane pestañas=new JTabbedPane();
 
        //Creamos el panel y lo añadimos a las pestañas
        JPanel panel1=new JPanel();
 
        //Componentes del panel1
        JLabel et_p1=new JLabel("Estas en el panel 1");
        panel1.add(et_p1);
 
        //Añadimos un nombre de la pestaña y el panel
        pestañas.addTab("Panel 1", panel1);
 
        //Realizamos lo mismo con el resto
        JPanel panel2=new JPanel();
        pestañas.addTab("Panel 2", panel2);
 
        //Componentes del panel2
        JLabel et_p2=new JLabel("Estas en el panel 2");
        panel2.add(et_p2);
 
        JPanel panel3=new JPanel();
 
        //Componentes del panel3
        JLabel et_p3=new JLabel("Estas en el panel 3");
        panel3.add(et_p3);
 
        pestañas.addTab("Panel 3", panel3);
 
        JPanel panel4=new JPanel();
 
        //Componentes del panel4
        JLabel et_p4=new JLabel("Estas en el panel 4");
        panel4.add(et_p4);
 
        pestañas.addTab("Panel 4", panel4);
 
        //getContentPane().add(pestañas);
        //add(pestañas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
